[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_student_intro_program = "HaZ6i8ytt2QxDdB3gZTriqYBF2JJSj1xn3V2X2vNn95J"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
